Traceback (most recent call last):
  File "run_rc_model.py", line 15, in <module>
    from statsd import statsd
ImportError: No module named statsd
